// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjFCIlyYRMKhknpWBCxL9pviIAODv5uqw',
    appId: '1:65372686673:web:b21bda25309d8951402b70',
    messagingSenderId: '65372686673',
    projectId: 'bio-sphere-aecc0',
    authDomain: 'bio-sphere-aecc0.firebaseapp.com',
    storageBucket: 'bio-sphere-aecc0.firebasestorage.app',
    measurementId: 'G-R3SDH8J4XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH9m3MmbO1kAr1rfAtdzGxWkaQU05isUE',
    appId: '1:65372686673:android:9c43a22a085aad28402b70',
    messagingSenderId: '65372686673',
    projectId: 'bio-sphere-aecc0',
    storageBucket: 'bio-sphere-aecc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8ZhNuPO2nWclwccncekEJ-rbKLpZjq4',
    appId: '1:65372686673:ios:d39c09c6f2dedf6f402b70',
    messagingSenderId: '65372686673',
    projectId: 'bio-sphere-aecc0',
    storageBucket: 'bio-sphere-aecc0.firebasestorage.app',
    iosBundleId: 'com.example.bioSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF8ZhNuPO2nWclwccncekEJ-rbKLpZjq4',
    appId: '1:65372686673:ios:d39c09c6f2dedf6f402b70',
    messagingSenderId: '65372686673',
    projectId: 'bio-sphere-aecc0',
    storageBucket: 'bio-sphere-aecc0.firebasestorage.app',
    iosBundleId: 'com.example.bioSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjFCIlyYRMKhknpWBCxL9pviIAODv5uqw',
    appId: '1:65372686673:web:c5f35eab9b31c9ac402b70',
    messagingSenderId: '65372686673',
    projectId: 'bio-sphere-aecc0',
    authDomain: 'bio-sphere-aecc0.firebaseapp.com',
    storageBucket: 'bio-sphere-aecc0.firebasestorage.app',
    measurementId: 'G-TQVJJ7C7DH',
  );
}
